### ISSUE TITLE
Diseñar Logo del grupo de trabajo

### ISSUE THREAD

**Issue by Daniers** [Daniers/Superior-Core#1]
Crear el logo del grupo de trabajo que va a realizar la aplicacion

**Comment by Daniers** [comment]
Mediante Corel draw, u otro Aplicativo de diseño gráfico, crear el icono del grupo de trabajo (Superior Core) https://github.com/Daniers/Superior-Core/blob/master/imgs/logo.png

**Comment by juandavidrey** [comment]
Mediante Corel draw, u otro Aplicativo de diseño gráfico, crear el icono del grupo de trabajo (Superior Core) https://github.com/Daniers/Superior-Core/blob/master/imgs/logo.png
git commit -m 'este es un mensaje close #'
