### ISSUE TITLE
Consultar email del usuario por cantidad

### ISSUE THREAD

**Issue by Daniers** [Daniers/Superior-Core#20]
Obtener el dato de la cantidad de correos electrónicos enviados por el usuario a otros que hacen parte del grupo.

**Comment by bayronortiz** [comment]
Ok. Tarea terminada.
Se ha realizado un script en python, que obtiene las credenciales y consulta los emails recibidos. Cuenta el número existente de emails recibidos de un emisor especifico.

Para ejecutar deben tener su archivo client_secrets.json, de su perfil.
