### ISSUE TITLE
Desarrollar un Login de Usuario

### ISSUE THREAD

**Issue by asleon93** [Daniers/Superior-Core#41]
Este Issue debe realizarse para la presentacion del siguente Sprint Review, debe constar de un login funcional de un Usuario de la aplicacion

**Comment by bayronortiz** [comment]
Este es un login sencillo, donde la aplicación solicita los permisos a Gmail y este le devuelve un código de autenticación para el acceso. Luego simplemente muestra un mensaje de bienvenida dentro de la ventana principal.
